### ISSUE TITLE
Remove potential leak

### ISSUE THREAD

**Issue by siaarzh** [elessarelfstone/oradump#1]
Delete TDR table example from `/templates` as it links to exiting production tables and shows schema.

I suggest recreating the repo without it. Create a new template with something simpler. Like a "students age and grades" table.

**Comment by elessarelfstone** [comment]
Yeah... that's a good point. I'm even thinking of moving templates from FS
to DB. Some ideas came up after our last conversation about extracting and
loading data(scheduling). First off we need structure our info of data
sources somehow. It could be like meta information for our future data
moving code, pipelines etc. Below  scheme that illustrate some starting
points. As you can see here we have field "Скрипт-шаблон" for every table.
[image: image.png]

**Comment by siaarzh** [comment]
I can see you fixed this already. But as I said, it's best to remove the this repo and start from the latest commit (delete the git history). That way, no information will stay online.
